dev

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,6 +33,10 @@ jobs:
       - name: Generate Allure Report
         run: npm run cy:gererate:allure
 
+      # Verificar a existência do relatório Allure
+      - name: Verify Allure Report
+        run: if [ ! -d "allure-report" ]; then echo "Allure report not found"; exit 1; fi
+
       # Upload do relatório Allure como artefato
       - name: Upload Allure Report
         uses: actions/upload-artifact@v3
